### ISSUE TITLE
JS-version

### ISSUE THREAD

**Issue by Merrick17** [HenrisonTao/ftx_grid_trading_bot#1]
Can you add a Node js version ? 
i've tried to do it by my self but couldn't

**Comment by HenrisonTao** [comment]
Hi, thanks for reaching. I don't have the plan to add JS version. If you have some problems building JS version, you can send mail to me or search the error message on google.

**Comment by HenrisonTao** [comment]
close the issue.

**Comment by HenrisonTao** [comment]
Hi, thanks for reaching. I don't have the plan to add JS version. If you have some problems building JS version, you can send mail to me or search the error message on google.
