### ISSUE TITLE
have been trying your code for sometime new a feature always buy sell only on postonly or limit order with maker fee

### ISSUE THREAD

**Issue by vensilver** [HenrisonTao/ftx_grid_trading_bot#2]
hello,

Need a feature always post only in maker fee if post only order is canceled then place an order above market rate.

**Comment by thiagocapuano** [comment]
I not understood, i not send any question about, i not tryied use feature

Em Seg, 9 de ago de 2021 00:39, vensilver ***@***.***>
escreveu:

**Comment by vensilver** [comment]
hello

FTX has a maker and taker fee for every trade.

I want the bot to always only sell and buy only in maker fee.

it has a field to post only on

**Comment by Menox10** [comment]
**params={"postOnly": True}**
 
if side =="buy":
        orderid = self.exchange.create_limit_buy_order(self.symbol,self.amount,price,**params** )["info"]["id"]
else:
         orderid = self.exchange.create_limit_sell_order(self.symbol,self.amount,price,**params** )["info"]["id"]
return orderid

**Comment by Menox10** [comment]
When post-only is True you are always market maker and do not have to pay fee (min 25 FTT)

**Comment by HenrisonTao** [comment]
@Menox10  Thanks for you explain it.
