### ISSUE TITLE
got public attention

### ISSUE THREAD

**Issue by changtimwu** [HenrisonTao/ftx_grid_trading_bot#4]
Well, not an issue really.  Just let you know this repo has being mentioned by Part Time Larry.

https://www.youtube.com/watch?v=QzqMGX4Qk1A&t=3m16s

**Comment by HenrisonTao** [comment]
> Well, not an issue really. Just let you know this repo has being mentioned by Part Time Larry.
> 
> https://www.youtube.com/watch?v=QzqMGX4Qk1A&t=3m16s

Thanks for your reminder. 😀
